<script setup>
import { ChevronLeft, BookOpen, Clock, Activity, Check, Lock, Sparkles } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { watch } from 'vue'
import ProgressRing from '../components/common/ProgressRing.vue'
import PBar from '../components/common/PBar.vue'
import SubjectBadge from '../components/common/SubjectBadge.vue'
import { useAppState } from '../state/appState'
const route=useRoute(); const router=useRouter(); const { selectedModule, moduleLessons, subjectColor, setModule }=useAppState(); setModule(route.params.moduleId); watch(() => route.params.moduleId, id => setModule(id))
function openLesson(l){ if(l.type==='simulation') router.push('/simulation'); else if(l.type==='quiz') router.push('/quiz'); else router.push('/lesson') }
</script>
<template><section class="page"><button class="back-btn" @click="router.push('/modules')"><ChevronLeft :size="16"/> All modules</button><div class="module-hero"><div><SubjectBadge :subject="selectedModule.subject"/><h1>{{selectedModule.title}}</h1><p>{{selectedModule.description}}</p><div class="module-meta"><span><BookOpen :size="15"/> {{selectedModule.lessons}} lessons</span><span><Clock :size="15"/> {{selectedModule.hours}} hours</span><span><Activity :size="15"/> {{selectedModule.difficulty}}</span></div></div><div class="detail-progress"><ProgressRing :pct="selectedModule.progress" :size="110" :sw="9" :color="subjectColor(selectedModule.subject)"/><b>{{selectedModule.progress}}%</b><small>Complete</small></div></div><div class="lesson-layout"><div class="panel lesson-list"><div class="panel-head"><div><h2>Module lessons</h2><p>Work through each activity in order</p></div></div><div v-for="(l,i) in moduleLessons" :key="l.id" class="module-lesson" @click="openLesson(l)"><div class="lesson-number" :class="{completed:l.completed}"><Check v-if="l.completed" :size="15"/><span v-else>{{i+1}}</span></div><div class="grow"><b>{{l.title}}</b><small>{{l.type==='simulation'?'Interactive simulation':l.type==='quiz'?'Quiz':'Reading'}} · {{l.duration}} min</small></div><span v-if="l.completed" class="status-pill done">Completed</span><span v-else-if="i===3" class="status-pill next">Next up</span><Lock v-else :size="15" class="muted"/></div></div><div class="side-stack"><div class="panel"><h3>Your progress</h3><PBar :pct="selectedModule.progress" color="#2c7a50" h="8"/><div class="progress-row"><span>Completed</span><b>{{Math.round(selectedModule.progress/100*selectedModule.lessons)}} / {{selectedModule.lessons}}</b></div></div><div class="panel tip"><Sparkles :size="18"/><div><b>Study tip</b><p>Short, focused sessions are easier to maintain. Try 20–30 minutes today.</p></div></div></div></div></section></template>
